### ISSUE TITLE
When prompted to allow my app access to photos, the app crashes.

### ISSUE THREAD

**Issue by dlush315** [jmkr/SimpleAssetPicker#1]
The error stems in the updateCachedAssets() function and originates at this line:

        /*
         Check if the collection view is showing an area that is significantly
         different to the last preheated area.
         */
        let delta = abs(CGRectGetMidY(preheatRect) - CGRectGetMidY(self.previousPreheatRect!))

Do you know of any possible explanations and/or fixes?

**Comment by jmkr** [comment]
Hi @dlush315 , thanks for pointing this out! The issue should be fixed in 0.2.0 -  let me know if you encounter the same problem again.
